apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-posts
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-posts
  template:
    metadata:
      labels:
        app: flask-posts
    spec:
      containers:
      - name: flask-posts
        image: docker.io/rvp0110/flask-posts:v2
        ports:
        - containerPort: 5000
        env:
        - name: SECRET_KEY
          value: "dev"
        - name: JWT_SECRET_KEY
          value: "dev"
        - name: DATABASE_URL
          value: "sqlite:///local.db"
