# k8s/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: flask-posts-secrets
type: Opaque
stringData:
  SECRET_KEY: "replace-me"
  JWT_SECRET_KEY: "replace-me-jwt"
  DATABASE_URL: "postgresql+psycopg2://user:pass@postgres:5432/flaskdb"
